const ResumeApi = [
  // Education (most recent first)
  {
    id: 1,
    category: "education",
    year: "4Geeks Academy Venezuela (Aug - Dec 2022)",
    title: "Full Stack Software Developer",
    desc: "Intensive bootcamp covering full-stack development: HTML, CSS, JavaScript, Python, SQL, React, Flask.",
    rate: "4.30/5",
  },
  {
    id: 2,
    category: "education",
    year: "Central University of Venezuela (Apr 2012 - Nov 2016)",
    title: "Marketing Specialist",
    desc: "Postgraduate specialization in business marketing, focused on strategic communication and market analysis.",
    rate: "4.50/5",
  },
  {
    id: 3,
    category: "education",
    year: "Simón Bolívar University (Sep 2003 - Feb 2009)",
    title: "Production Engineer",
    desc: "Bachelor's degree in production engineering, emphasizing process optimization and industrial systems.",
    rate: "4.80/5",
  },

  // Experience (most recent first)
  {
    id: 4,
    category: "experience",
    year: "Atenas Grupo Consultor (Jan 2025 - Nov25)",
    title: "IT Development Lead",
    desc: "Lead multidisciplinary development teams, coordinate daily activities, integrate external projects, and promote emerging technologies.",
    rate: "5.00/5",
  },
  {
    id: 5,
    category: "experience",
    year: "EmpathyAI (Apr 2024 - Mar 2025)",
    title: "Full Stack Developer",
    desc: "Built responsive UIs with React and Next.js, integrated AI APIs, designed scalable architectures, and connected Azure CosmosDB and Blob Storage.",
    rate: "4.85/5",
  },
  {
    id: 6,
    category: "experience",
    year: "The Empire (Aug 2024 - Sep 2024)",
    title: "WordPress Developer",
    desc: "Created and customized websites using Elementor and Figma. Installed plugins, optimized performance, and implemented SEO strategies.",
    rate: "4.60/5",
  },
  {
    id: 7,
    category: "experience",
    year: "LinkedTeam (Dec 2022 - Dec 2024)",
    title: "Full Stack Web Developer (Freelance)",
    desc: "Developed a full-stack SaaS app for insurance managers. Built CRM, Kanban, training modules, and manager dashboards using React, Flask, and PostgreSQL.",
    rate: "4.90/5",
  },
  {
    id: 8,
    category: "experience",
    year: "Kentron (Aug 2023 - Mar 2024)",
    title: "Web Developer",
    desc: "Migrated ERP system for SENIAT. Delivered 19 user stories, resolved 20+ QA issues, and built reusable components with React, Redux, and Material UI.",
    rate: "4.70/5",
  },
  {
    id: 9,
    category: "experience",
    year: "Ridery (Oct 2021 - Jan 2022)",
    title: "Account Executive",
    desc: "Acquired 42 corporate clients and generated $7,423 in revenue through prospecting and effective sales presentations.",
    rate: "4.75/5",
  },
  {
    id: 10,
    category: "experience",
    year: "Citizens Inc. (Sep 2017 - Sep 2021)",
    title: "International Financial Advisor",
    desc: "Built a personal client portfolio through cold calling and follow-ups. Closed sales and recruited new advisors.",
    rate: "4.80/5",
  },
  {
    id: 11,
    category: "experience",
    year: "FTG Investing & Consulting (Nov 2018 - Aug 2019)",
    title: "Marketing & Advertising Coordinator",
    desc: "Managed marketing requirements across consortium companies, coordinating digital, outdoor, and trade marketing efforts.",
    rate: "4.65/5",
  },
  {
    id: 12,
    category: "experience",
    year: "Samsung Electronics (Aug 2016 - Aug 2017)",
    title: "Key Account Manager",
    desc: "Managed B2B relationships with distributors and retailers. Oversaw credit, logistics, and product rotation to meet sales quotas.",
    rate: "5.00/5",
  },
  {
    id: 13,
    category: "experience",
    year: "Movistar (Apr 2013 - Jul 2016)",
    title: "Retention & Acquisition Leader",
    desc: "Led customer loyalty programs and mobile internet acquisition campaigns. Increased ARPU and exceeded client acquisition goals.",
    rate: "4.95/5",
  },
  {
    id: 14,
    category: "experience",
    year: "LG Electronics (May 2012 - Jan 2013)",
    title: "Key Account Executive",
    desc: "Achieved $12MM in sales and increased distributor performance by 35%. Managed credit and logistics for B2B clients.",
    rate: "4.90/5",
  },
  {
    id: 15,
    category: "experience",
    year: "LG Electronics (Jun 2010 - Apr 2012)",
    title: "Product Executive – Mobile Devices",
    desc: "Promoted LG mobile products across national carriers. Delivered training and presentations to boost channel rotation.",
    rate: "4.85/5",
  },
  {
    id: 16,
    category: "experience",
    year: "Nielsen (Feb 2009 - Jun 2010)",
    title: "Account Executive – Market Research",
    desc: "Delivered performance reports for clients like PEPSICO and LG Mobile. Provided strategic insights using Nielsen Advisor software.",
    rate: "4.75/5",
  },
];

export default ResumeApi;
